words_by_level = {
    "easy": [
        "cat","dog","bat","hat","rat","mat","sat","fat","pat","vat",
        "can","ban","fan","man","pan","ran","tan","van","dan","jan",
        "bed","red","fed","led","wed","ted","ned","ped","sed","hed",
        "big","dig","fig","gig","jig","pig","rig","wig","zig","twig",
        "box","fox","hot","lot","not","pot","rot","dot","got","cot",
        "bug","dug","hug","jug","mug","pug","rug","tug","lug","slug",
        "arm","art","bar","car","far","jar","tar","war","par","star",
        "age","ace","ape","are","ate","axe","eye","ice","ore","use",
        "bay","day","gay","hay","jay","lay","may","pay","ray","say",
        "bee","fee","see","tee","wee","free","tree","knee","flee","glee",
        "bow","cow","how","low","mow","now","row","sow","tow","vow",
        "boy","joy","toy","coy","ploy","troy","ahoy","buoy","cloy","decoy",
        "cup","pup","sup","up","yup","dup","gup","lup","nup","tup",
        "cut","but","gut","hut","jut","nut","put","rut","tut","glut",
        "dip","hip","lip","nip","rip","sip","tip","zip","chip","drip",
        "bit","fit","hit","kit","lit","pit","sit","wit","grit","spit",
        "cap","gap","lap","map","nap","rap","sap","tap","zap","clap",
        "den","hen","men","pen","ten","yen","zen","glen","then","when",
        "dim","him","rim","vim","swim","trim","slim","brim","grim","prim",
        "fin","bin","gin","kin","pin","sin","tin","win","chin","grin",
    ],
    "medium_easy": [
        "able","acid","aged","also","area","army","away","baby","back","ball",
        "band","bank","base","bath","bear","beat","been","bell","best","bird",
        "blow","blue","boat","body","bomb","bond","bone","book","boom","born",
        "both","bowl","burn","bush","busy","call","calm","came","card","care",
        "case","cash","cast","cave","cell","chat","chef","chip","city","clap",
        "clay","clip","club","coal","coat","code","coil","cold","come","cook",
        "cool","cope","copy","core","corn","cost","coup","crew","crop","cure",
        "dark","data","date","dawn","days","dead","deal","dear","debt","deck",
        "deep","deny","desk","diet","dirt","dish","disk","dock","does","done",
        "door","dose","down","draw","drew","drop","drug","drum","dual","dull",
        "dump","dusk","dust","duty","each","earn","ease","east","edge","else",
        "emit","epic","even","ever","evil","exam","exit","face","fact","fail",
        "fair","fall","fame","farm","fast","fate","fear","feel","feet","fell",
        "felt","file","fill","film","find","fine","fire","firm","fish","fist",
        "flag","flat","flew","flip","flow","foam","fold","folk","fond","font",
        "food","fool","foot","ford","fore","fork","form","fort","foul","four",
        "free","from","fuel","full","fund","fuse","gain","game","gang","gate",
        "gave","gaze","gear","gift","girl","give","glad","glow","glue","goal",
        "goes","gold","golf","gone","good","grab","gray","grew","grid","grin",
        "grip","grow","gulf","guru","gust","guys","hack","hair","half","hall",
        "halt","hand","hang","hard","harm","hate","have","head","heal","heap",
        "heat","heel","held","help","herb","here","hero","hide","high","hill",
        "hint","hire","hold","hole","holy","home","hood","hook","hope","horn",
        "host","hour","huge","hull","hunt","hurt","icon","idea","idle","inch",
        "into","iron","isle","item","jail","jazz","join","joke","jump","just",
        "keen","keep","kick","kill","kind","king","kiss","knew","knit","know",
        "lack","lady","lake","lamp","land","lane","last","late","lawn","lead",
        "leaf","lean","leap","left","lend","lens","less","lick","life","lift",
        "like","lime","line","link","lion","list","live","load","loan","lock",
        "loft","logo","long","look","loop","lord","lore","lose","loss","lost",
        "loud","love","luck","lung","lure","lurk","made","mail","main","make",
        "male","mall","malt","many","mark","mars","mask","mass","mast","math",
        "maze","meal","mean","meat","meet","melt","memo","menu","mere","mesh",
        "mild","mile","milk","mill","mind","mine","mint","miss","mode","mold",
        "moon","more","most","move","much","must","myth","nail","name","navy",
        "near","neck","need","nest","news","next","nice","nine","node","none",
        "noon","norm","nose","note","noun","nude","null","oath","obey","odds",
        "once","only","open","oral","over","oven","pace","pack","page","paid",
        "pain","pair","pale","palm","park","part","pass","past","path","peak",
        "peel","peer","pick","pile","pill","pine","pink","pipe","plan","play",
        "plot","plow","plug","plus","poem","poet","pole","poll","pond","pool",
        "poor","port","pose","post","pour","pray","prey","pull","pump","pure",
        "push","quit","race","rack","rage","raid","rail","rain","rank","rare",
        "rate","read","real","reap","rear","rely","rent","rest","rice","rich",
        "ride","ring","rise","risk","road","roam","roar","rock","role","roll",
        "roof","room","root","rope","rose","ruin","rule","rush","rust","safe",
        "sage","sail","sake","sale","salt","same","sand","sane","sang","sank",
        "save","scan","scar","seal","seam","seat","seed","seek","seem","seen",
        "self","sell","send","sent","shed","ship","shoe","shop","shot","show",
        "shut","sick","side","sigh","sign","silk","sing","sink","site","size",
        "skin","skip","slam","slap","slim","slip","slow","slug","snap","snow",
        "soak","soap","soar","sock","soft","soil","sold","sole","some","song",
        "soon","sort","soul","soup","sour","span","spin","spot","spur","star",
        "stay","stem","step","stir","stop","stub","such","suit","sung","sunk",
        "sure","surf","swap","swim","tail","take","tale","talk","tall","tank",
        "task","team","tear","tell","tend","tent","term","test","text","than",
        "that","them","then","they","thin","this","thus","tide","tied","tier",
        "till","time","tiny","tire","toad","told","toll","tomb","tone","took",
        "tool","tops","tore","torn","toss","tour","town","trap","tree","trim",
        "trip","true","tube","tuck","tune","turn","twin","type","ugly","undo",
        "unit","upon","used","user","vary","vast","veil","verb","very","vest",
        "view","vine","visa","void","volt","vote","wade","wage","wait","wake",
        "walk","wall","wand","want","ward","warm","warn","warp","wash","wave",
        "weak","weal","wean","wear","weed","week","well","went","were","west",
        "what","when","whip","whom","wide","wife","wild","will","wind","wine",
        "wing","wink","wire","wise","wish","with","woke","wolf","wood","word",
        "wore","work","worm","worn","wrap","wren","writ","yard","year","yell",
        "your","zero","zone","zoom",
    ],
    "medium": [
        "about","above","abuse","actor","acute","admit","adopt","adult","after","again",
        "agent","agree","ahead","alarm","album","alert","alien","align","alike","alive",
        "alley","allow","alone","along","alter","angel","anger","angle","angry","anime",
        "ankle","annex","apart","apple","apply","arena","argue","arise","armor","aroma",
        "arose","array","arrow","aside","asset","atlas","attic","audio","audit","avoid",
        "awake","award","aware","awful","badly","baker","basic","basis","batch","beach",
        "began","begin","being","below","bench","bible","birth","black","blade","blame",
        "bland","blank","blast","blaze","bleed","blend","bless","blind","block","blood",
        "bloom","blown","board","bonus","boost","booth","bound","boxer","brace","brain",
        "brand","brave","bread","break","breed","brick","bride","brief","bring","broad",
        "broke","brook","brown","brush","build","built","bunch","burst","buyer","cabin",
        "cable","camel","candy","carry","catch","cause","chain","chair","chaos","charm",
        "chase","cheap","check","cheek","cheer","chess","chest","chief","child","china",
        "choir","chord","chose","civic","civil","claim","class","clean","clear","clerk",
        "click","cliff","climb","cling","clock","clone","close","cloth","cloud","coach",
        "coast","cobra","color","comic","comma","coral","could","count","court","cover",
        "crack","craft","crane","crash","crazy","cream","creek","crime","crisp","cross",
        "crowd","crown","cruel","crush","curve","cycle","daily","dance","death","debut",
        "delay","delta","dense","depot","depth","derby","devil","digit","dirty","disco",
        "ditch","diver","dizzy","dodge","doing","doubt","dough","draft","drain","drama",
        "drank","drawn","dream","dress","dried","drift","drink","drive","drove","drown",
        "dying","eager","eagle","early","earth","eight","elite","empty","enemy","enjoy",
        "enter","entry","equal","error","essay","event","every","exact","exist","extra",
        "fable","faint","faith","false","fancy","fatal","fault","feast","fence","fever",
        "fiber","field","fifth","fifty","fight","final","first","fixed","flame","flash",
        "flesh","float","flood","floor","flour","fluid","flush","focus","force","forge",
        "forth","forum","found","frame","frank","fraud","fresh","front","frost","froze",
        "fruit","fully","funny","ghost","giant","given","glass","globe","gloom","glory",
        "glove","going","grace","grade","grain","grand","grant","grape","grasp","grass",
        "grave","great","green","greet","grief","grind","groan","gross","group","grove",
        "guard","guess","guest","guide","guild","guilt","guise","gusto","habit","happy",
        "harsh","haste","haven","heart","heavy","hence","herbs","hinge","hippo","honor",
        "horse","hotel","house","human","humor","hurry","hyper","ideal","image","imply",
        "inbox","index","indie","infer","inner","input","inter","intro","issue","ivory",
        "jewel","joint","joker","judge","juice","juicy","karma","knife","knock","known",
        "label","large","laser","later","laugh","layer","learn","lease","least","leave",
        "legal","lemon","level","light","limit","linen","liver","local","lodge","logic",
        "loose","lover","lower","lucky","lunar","lunch","lyric","magic","major","maker",
        "manor","maple","march","match","mayor","media","mercy","merit","metal","might",
        "minor","minus","model","money","month","moral","motor","mount","mouse","mouth",
        "movie","music","naive","nerve","never","night","ninja","noble","noise","north",
        "noted","novel","nurse","nylon","occur","ocean","offer","often","olive","onset",
        "opera","orbit","order","other","outer","owner","oxide","ozone","paint","panel",
        "panic","paper","party","pasta","patch","pause","peace","pearl","pedal","penny",
        "phase","phone","photo","piano","piece","pilot","pitch","pixel","pizza","place",
        "plain","plane","plant","plate","plaza","plead","pluck","plumb","plume","plunge",
        "point","polar","poppy","power","press","price","pride","prime","print","prior",
        "prize","probe","prone","proof","prose","proud","prove","psalm","pulse","pupil",
        "queen","query","quest","queue","quick","quiet","quota","quote","radar","radio",
        "raise","rally","ranch","range","rapid","ratio","reach","ready","realm","rebel",
        "refer","reign","relax","repay","reply","rider","ridge","rifle","right","risky",
        "rival","river","robin","robot","rocky","rouge","rough","round","route","royal",
        "rugby","ruler","rural","sadly","saint","salad","sauce","scale","scene","scope",
        "score","scout","sense","serve","seven","shade","shake","shall","shame","shape",
        "share","shark","sharp","sheep","sheer","shelf","shell","shift","shine","shirt",
        "shock","shore","short","shout","sight","since","sixth","sixty","skill","skull",
        "slate","slave","sleep","slice","slide","slope","smart","smell","smile","smoke",
        "snake","solar","solid","solve","sorry","south","space","spare","spark","speak",
        "speed","spend","spice","spike","spine","spite","split","spoke","spoon","sport",
        "spray","squad","stack","staff","stage","stain","stale","stand","stark","start",
        "state","steak","steal","steam","steel","steep","steer","stick","stiff","still",
        "stock","stone","stood","store","storm","story","stove","strap","straw","stray",
        "strip","stuck","study","stuff","style","sugar","suite","sunny","super","surge",
        "swamp","swear","sweep","sweet","swept","swift","sword","swore","sworn","syrup",
        "table","taste","teach","teeth","thank","theme","there","thick","thing","think",
        "third","those","three","threw","throw","thumb","tiger","tight","timer","tired",
        "title","today","token","topic","total","touch","tough","towel","tower","toxic",
        "trace","track","trade","trail","train","trait","tramp","trash","treat","trend",
        "trial","tribe","trick","tried","troop","truck","truly","trump","trunk","trust",
        "truth","tumor","tuner","twice","twist","tying","ultra","uncle","under","unify",
        "union","unity","until","upper","upset","urban","usage","usual","utter","valid",
        "value","valve","video","vigor","viral","virus","visit","vista","vital","vivid",
        "vocal","voice","voter","vague","wagon","waste","watch","water","weary","weave",
        "wedge","weigh","weird","whale","wheat","wheel","where","which","while","white",
        "whole","whose","wider","witch","woman","women","world","worry","worse","worst",
        "worth","would","wound","wrath","write","wrote","yacht","young","youth","zebra",
    ],
    "hard": [
        "abandon","ability","absence","academy","account","accused","achieve","acquire",
        "address","advance","adverse","advised","against","airline","airport","alcohol",
        "already","ancient","another","anxiety","anybody","applied","arrange","arrival",
        "article","assault","attempt","attract","auction","average","awesome","balance",
        "barrier","battery","because","bedroom","believe","benefit","between","billion",
        "biology","blanket","blossom","brother","brought","cabinet","captain","capture",
        "careful","carrier","catalog","century","certain","chapter","charity","chicken",
        "circuit","citizen","classic","climate","cluster","collect","college","combine",
        "comfort","command","comment","company","compare","compete","complex","concept",
        "concern","conduct","confirm","connect","consent","contain","content","contest",
        "control","convert","correct","council","country","courage","covered","created",
        "culture","current","curtain","customs","cutting","damaged","dealing","decided",
        "declare","defense","deliver","density","deposit","deserve","despite","develop",
        "digital","disease","display","distant","divided","dolphin","drawing","dynamic",
        "economy","edition","element","emotion","emperor","endless","enforce","enhance",
        "episode","essence","evening","examine","example","excited","execute","exhibit",
        "explain","explore","express","extreme","factory","failure","fantasy","fashion",
        "feature","feeling","fiction","finance","finding","fitness","foreign","forever",
        "formula","forward","freedom","further","gallery","general","genuine","gesture",
        "getting","glimpse","glitter","goddess","gravity","growing","habitat","harmony",
        "harvest","healthy","history","holiday","horizon","however","hundred","hunting",
        "husband","imagine","improve","include","initial","inspire","install","instead",
        "intense","involve","journey","justice","kingdom","kitchen","knowing","landing",
        "largely","lasting","leading","learned","leaving","library","limited","logical",
        "machine","manager","maximum","meaning","measure","medical","meeting","mention",
        "message","million","minimum","miracle","mission","mixture","monitor","morning",
        "mystery","natural","network","nothing","nuclear","obvious","officer","opinion",
        "outside","overall","package","partner","passion","patient","pattern","payment",
        "perfect","perform","perhaps","picture","plastic","popular","portion","poverty",
        "present","prevent","primary","private","problem","process","produce","product",
        "program","project","protect","provide","purpose","quality","quarter","quickly",
        "reality","receive","recover","reflect","release","replace","require","respect",
        "respond","restore","revenue","reverse","routine","running","science","section",
        "service","setting","several","shelter","similar","society","someone","special",
        "station","storage","strange","student","subject","success","suggest","support",
        "surface","survive","teacher","tension","through","tonight","tourism","towards",
        "traffic","trouble","typical","uniform","unknown","unusual","upgrade","version",
        "village","violent","virtual","visible","waiting","walking","warning","weather",
        "website","welcome","western","whether","without","working","writing","younger",
        "absolute","abstract","academic","accident","accurate","achieved","acquired",
        "activity","actually","addition","adequate","adjusted","admitted","advanced",
        "affected","aircraft","alliance","although","analysis","announce","anything",
        "anywhere","approach","approval","argument","assembly","attached","audience",
        "backbone","balanced","becoming","behavior","birthday","boundary","breaking",
        "building","business","calendar","campaign","capacity","category","champion",
        "changing","chemical","children","choosing","circular","climbing","clothing",
        "coaching","collapse","colonial","combined","commerce","complete","computer",
        "conflict","congress","consider","constant","consumer","continue","contract",
        "contrary","convince","coverage","creating","criminal","critical","cultural",
        "database","daughter","deadline","decision","decrease","defeated","delivery",
        "describe","designed","detailed","dialogue","directly","disaster","discover",
        "distance","distinct","document","dominant","dramatic","duration","educated",
        "election","electric","emerging","emphasis","employed","engineer","enormous",
        "entering","equality","estimate","evaluate","evidence","exchange","exercise",
        "existing","expected","extended","external","familiar","feedback","festival",
        "fighting","followed","football","fraction","fragment","frequent","function",
        "generate","generous","grateful","greatest","guidance","handling","happened",
        "hardware","headline","heritage","hospital","identify","ideology","increase",
        "indicate","industry","informal","informed","instance","interest","internal",
        "interval","involved","isolated","judgment","keyboard","language","learning",
        "lifetime","likewise","location","majority","marriage","material","medicine",
        "military","moderate","momentum","moreover","movement","multiple","national",
        "negative","northern","notebook","occasion","official","operator","opposite",
        "ordinary","organize","original","overcome","painting","parallel","peaceful",
        "personal","physical","platform","pleasant","politics","positive","possible",
        "powerful","practice","pressure","previous","princess","priority","probably",
        "progress","property","proposal","province","purchase","question","reaction",
        "recently","recovery","regional","relation","relative","relevant","religion",
        "remember","research","resource","response","restrict","resulted","revealed",
        "security","selected","sentence","sequence","shortage","shoulder","simplify",
        "situated","skeleton","software","solution","somebody","southern","specific",
        "spectrum","standard","starting","strategy","strength","struggle","suddenly",
        "suitable","superior","surprise","survival","teaching","terminal","thinking",
        "thousand","together","tomorrow","transfer","treasure","triangle","ultimate",
        "umbrella","universe","vacation","valuable","variable","velocity","whatever",
        "whenever","wherever","wildlife","wireless","withdraw","yourself",
    ],
    "expert": [
        "abandoned","abilities","abolition","abundance","academics","accidental","accomplish",
        "according","accounted","achieving","activated","addiction","addressed","admission",
        "adventure","adversity","affection","afternoon","agreement","algorithm","alignment",
        "allowance","alongside","ambiguous","ambitious","amendment","amplified","animation",
        "announced","anonymous","apartment","apparatus","appealing","appointed","architect",
        "arguments","assembled","assertion","assistant","associate","astronomy","attention",
        "attribute","authority","available","awareness","beautiful","beginning","benchmark",
        "biography","blueprint","breakdown","broadcast","calculate","candidate","capability",
        "carefully","celebrate","challenge","character","chemistry","childhood","chocolate",
        "chronicle","classical","classroom","clearance","coalition","cognitive","collected",
        "commander","community","companion","completed","component","computing","concerned",
        "condition","confident","confirmed","connected","conscious","construct","contained",
        "continued","corporate","correctly","countless","courtyard","dangerous","dedicated",
        "democracy","dependent","described","developed","different","difficult","dimension",
        "direction","discovery","discussed","displayed","diversity","dominated","education",
        "effective","efficient","elaborate","emergency","emotional","emphasize","encounter",
        "encourage","enjoyment","essential","establish","evolution","excellent","exception",
        "exclusive","executive","existence","expansion","expensive","explained","expressed",
        "extensive","extremely","fantastic","financial","following","formation","framework",
        "frequency","generated","geography","gradually","guarantee","happiness","highlight",
        "historical","household","hurricane","identical","important","impressed","including",
        "increased","indicated","influence","initially","inspiring","integrity","intention",
        "introduce","invention","knowledge","landscape","leadership","legendary","lifestyle",
        "lightning","listening","literally","locations","machinery","magnitude","marketing",
        "mechanism","mentioned","migration","milestone","motivated","mountains","narrative",
        "necessary","negotiate","objective","obstacles","operation","organized","otherwise",
        "ownership","paragraph","parameter","partially","passenger","performed","permanent",
        "permitted","phenomena","political","potential","practical","precisely","preferred",
        "presented","principle","procedure","professor","protected","published","qualified",
        "reasoning","recognize","recommend","recording","reference","reflected","regarding",
        "regularly","remaining","renewable","represent","requested","resources","respected",
        "resulting","returning","revealing","satisfied","scattered","scheduled","scientist",
        "secondary","sensitive","separated","seriously","signature","situation","somewhere",
        "spiritual","statement","structure","submitted","substance","suggested","supported",
        "surprised","sustained","technical","temporary","territory","therefore","thousands",
        "tolerance","tradition","transform","treatment","typically","uncertain","universal",
        "unlimited","unrelated","variation","volunteer","wonderful","yesterday",
        "accomplishment","administration","approximately","architecture","communication",
        "concentration","consideration","demonstration","determination","development",
        "differentiate","disappointment","documentation","encouragement","entertainment",
        "environmental","establishment","extraordinary","implementation","independence",
        "infrastructure","investigation","manufacturing","misunderstanding","organization",
        "participation","philosophical","possibilities","professional","qualification",
        "recommendation","responsibility","sophisticated","transformation","understanding",
        "unfortunately","visualization","vulnerability",
    ]
}

def get_words_for_level(level):
    if level <= 10:
        pool = words_by_level["easy"]
    elif level <= 30:
        pool = words_by_level["easy"] + words_by_level["medium_easy"]
    elif level <= 60:
        pool = words_by_level["medium_easy"] + words_by_level["medium"]
    elif level <= 80:
        pool = words_by_level["medium"] + words_by_level["hard"]
    else:
        pool = words_by_level["hard"] + words_by_level["expert"]
    return pool

def get_missing_count(level):
    if level <= 5:
        return 1
    elif level <= 15:
        return 1
    elif level <= 30:
        return 2
    elif level <= 50:
        return 2
    elif level <= 70:
        return 3
    elif level <= 85:
        return 3
    else:
        return 4
